CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description text,
    slug varchar(255) NOT NULL
);

CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    category_id bigint NOT NULL,
    description varchar(100) NOT NULL,
    full_description text,
    price numeric(9,2) NOT NULL,
    currency varchar(3) NOT NULL,
    image varchar(255),
    slug varchar(255),
    CONSTRAINT fk_categories FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT uq_product_slug UNIQUE (slug)
);

CREATE TABLE reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL,
    user_id bigint,
    author_name varchar(60) NOT NULL,
    content text,
    CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE baskets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp NOT NULL
);

CREATE TABLE basket_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL,
    quantity int,
    basket_id bigint NOT NULL,
    CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_basket_id FOREIGN KEY (basket_id) REFERENCES baskets(id)
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL UNIQUE,
    password varchar(500) NOT NULL,
    enabled boolean NOT NULL,
    image varchar(255),
    hash varchar(120),
    hash_date timestamp
);

CREATE TABLE authorities (
    username varchar(50) NOT NULL,
    authority varchar(50) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users (username)
);

CREATE UNIQUE INDEX ix_auth_username ON authorities (username, authority);

CREATE TABLE shipments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64) NOT NULL,
    price numeric(6,2) NOT NULL,
    type varchar(32) NOT NULL,
    default_shipment boolean DEFAULT false
);

CREATE TABLE payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64) NOT NULL,
    type varchar(32) NOT NULL,
    default_payment boolean DEFAULT false,
    note text
);

CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_date timestamp NOT NULL,
    order_status varchar(32) NOT NULL,
    gross_value numeric(15,2) NOT NULL,
    first_name varchar(30) NOT NULL,
    last_name varchar(30) NOT NULL,
    street varchar(60) NOT NULL,
    city varchar(30) NOT NULL,
    zip_code varchar(10) NOT NULL,
    email varchar(60) NOT NULL,
    phone varchar(20) NOT NULL,
    payment_id bigint,
    user_id bigint,
    CONSTRAINT fk_payment_id FOREIGN KEY (payment_id) REFERENCES payments(id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE order_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    product_id bigint,
    shipment_id bigint,
    quantity int NOT NULL,
    price numeric(15,2) NOT NULL,
    CONSTRAINT fk_order_id FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_shipment_id FOREIGN KEY (shipment_id) REFERENCES shipments(id),
    CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE order_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    created timestamptz NOT NULL,
    note text
);

-- Zdjęcia produktów/profili trzymane w bazie (bytea jest TOASTowane, więc
-- duże obrazy lądują poza stroną tabeli i nie spowalniają skanów po metadanych).
CREATE TABLE product_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    content_type varchar(100) NOT NULL,
    data bytea NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_product_images_name UNIQUE (name)
);
